Feature/link
1kkobayashi/sample_app pull request #25
Opened 2019-03-25 09:11 UTC by 1kkobayashi

fix #24 

・Log inのリンクは、進んでから作ります（第8章）
・テストはRspecで後でします。

2019-03-25 19:30 UTC, baibai25 reviewed
Good work! You should write comments in your source code.

2019-03-26 10:24 UTC, 1kkobayashi commented
> Good work! You should write comments in your source code.

安倍さん　コメントを追加いたしました。これでよろしいでしょうか。

2019-03-26 17:48 UTC, baibai25 commented
@1kkobayashi まだ簡単だから理解できると思うけれど（やってること分からんけど）、これからもっと難しいコードを書くだろうし、ビジネスでも書いていくのだから、どこでどんな処理をしているのか、コメントを書く癖をつけてくださいね。数カ月後、数年後に誰が見ても、理解できるようなドキュメントを書ける能力は重要だと思います。（できれば英語で）

2019-03-27 09:29 UTC, 1kkobayashi commented
@baibai25 アドバイスありがとうございます。以後コメントするよう心掛けます。

2019-03-27 11:18 UTC, a-tommyyy requested changes
これは何のPRなんでしょう．
rails tutorialの内容は自分は忘れてしまっているので，PRのtitleとdescriptionに最低限でも目的とやったことが入っているとコードを見たときに何のための実装なのか推測できて助かります．

あとCSSなどの画面の見た目に関するPRのときスクリーンショットがあると短時間でレビューができるので助かります．

2019-03-27 12:33 UTC, 1kkobayashi commented
@atomiyama  分かりにくく申し訳ありません。PRのtitleとdescriptionを修正いたしました。こちらの修正でよろしいでしょうか。

2019-03-29 08:16 UTC, a-tommyyy approved these changes

2019-03-29 08:16 UTC, atomiyama commented
LGTM~~~~~

2019-03-30 06:13 UTC, merged