5.4 ユーザー登録: 最初のステップ
1kkobayashi/sample_app pull request #28
Opened 2019-03-30 07:04 UTC by 1kkobayashi

fix #26 

ユーザー登録ページ(sign up)へのルーティングを作成し、ユーザー登録ページへのリンクを追加する。

2019-03-30 09:20 UTC, a-tommyyy requested changes

2019-03-30 09:20 UTC, atomiyama commented on config/routes.rb
> -  resources :fans
これを消すなら該当するmodelとかcontrollerとかも削除しておいたほうが良さそう．
使われていないcontrollerがあるのは良くない

2019-03-30 10:03 UTC, 1kkobayashi commented on config/routes.rb
> -  resources :fans
間違って消してました。直します！後で不具合でたら修正します！

2019-03-30 12:47 UTC, atomiyama commented on config/routes.rb
> -  resources :fans
消したことを指摘しているんじゃなくて，
routeを参照して，該当のcontrollerのアクションが呼ばれるというrailsの仕組みなんだから
どのrouteからも呼ばれていないcontrollerがあるのは汚いから合わせて消してという話．

あと不具合でたら修正するというスタンスは危ないからやめよう．
不具合でないようにテスト書いて実装するのであるから．

正当な理由がないならrouteを消すのであればcontrollerも合わせて消すべき．

2019-03-30 14:59 UTC, 1kkobayashi commented on config/routes.rb
> -  resources :fans
ご指摘ありがとうございます。以後気をつけます。

2019-03-30 16:19 UTC, atomiyama commented on config/routes.rb
> -  resources :fans
消したいからrouteを消したのだと思ったのだけど.
このrouteに該当するcontrollerを消すべきなんじゃ？

2019-03-31 06:51 UTC, 1kkobayashi commented on config/routes.rb
> -  resources :fans
冨山さんが作ってくださったものなので後々参考になると思って残しておきたいと思ってます。消したのは、本当に不注意でuserのrouteとかを編集、確認しようとした時に消してしまった感じです…消すときは指摘された通りにcontrollerやmodelも削除します。

2019-03-31 13:42 UTC, atomiyama commented
理解！LGTM
敬語やめないとあんばいに説教されるよ

2019-03-31 14:10 UTC, 1kkobayashi commented
@atomiyama 
ありがとう！大丈夫今VTuberのLIVE配信みてると思うから………

2019-03-31 14:10 UTC, merged

2019-03-31 15:38 UTC, baibai25 commented
気をつけないとプルリク、rejectしますからね : )